// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card/Card.vue')['default']
    CardContainer: typeof import('./src/components/card/CardContainer.vue')['default']
    Comment: typeof import('./src/components/comment/Comment.vue')['default']
    CommentCard: typeof import('./src/components/comment/CommentCard.vue')['default']
    Music: typeof import('./src/components/music/Music.vue')['default']
    Release: typeof import('./src/components/comment/Release.vue')['default']
  }
}

export { }
